/* This file is automatically generated
   from ../ports/sysdeps/arm/libm-test-ulps with gen-libm-test.pl.
   Don't change it - change instead the master files.  */


/* Maximal error of functions.  */
#define DELTAasin CHOOSE(0, 1, 2, 0, 1, 2)	/* asin  */
#define DELTAatanh CHOOSE(0, 1, 0, 0, 1, 0)	/* atanh  */
#define DELTAcabs CHOOSE(0, 1, 1, 0, 1, 1)	/* cabs  */
#define DELTAcacos CHOOSE(0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (1, 1), 0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (1, 1))	/* cacos  */
#define DELTAcacosh CHOOSE(0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (7, 3), 0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (7, 3))	/* cacosh  */
#define DELTAcasin CHOOSE(0, BUILD_COMPLEX (3, 0), BUILD_COMPLEX (2, 1), 0, BUILD_COMPLEX (3, 0), BUILD_COMPLEX (2, 1))	/* casin  */
#define DELTAcasinh CHOOSE(0, BUILD_COMPLEX (5, 3), BUILD_COMPLEX (1, 6), 0, BUILD_COMPLEX (5, 3), BUILD_COMPLEX (1, 6))	/* casinh  */
#define DELTAcatan CHOOSE(0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (4, 1), 0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (4, 1))	/* catan  */
#define DELTAcatanh CHOOSE(0, BUILD_COMPLEX (4, 1), BUILD_COMPLEX (1, 6), 0, BUILD_COMPLEX (4, 1), BUILD_COMPLEX (1, 6))	/* catanh  */
#define DELTAcbrt CHOOSE(0, 1, 0, 0, 1, 0)	/* cbrt  */
#define DELTAccos CHOOSE(0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (0, 1), 0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (0, 1))	/* ccos  */
#define DELTAccosh CHOOSE(0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (1, 1), 0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (1, 1))	/* ccosh  */
#define DELTAcexp CHOOSE(0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (1, 1), 0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (1, 1))	/* cexp  */
#define DELTAclog CHOOSE(0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (0, 3), 0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (0, 3))	/* clog  */
#define DELTAclog10 CHOOSE(0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (1, 5), 0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (1, 5))	/* clog10  */
#define DELTAcos CHOOSE(0, 2, 1, 0, 2, 1)	/* cos  */
#define DELTAcpow CHOOSE(0, BUILD_COMPLEX (1, 1.1031), BUILD_COMPLEX (4, 2), 0, BUILD_COMPLEX (1, 1.1031), BUILD_COMPLEX (4, 2))	/* cpow  */
#define DELTAcsin CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* csin  */
#define DELTAcsinh CHOOSE(0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (1, 1), 0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (1, 1))	/* csinh  */
#define DELTAcsqrt CHOOSE(0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (1, 1), 0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (1, 1))	/* csqrt  */
#define DELTActan CHOOSE(0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (1, 1), 0, BUILD_COMPLEX (1, 1), BUILD_COMPLEX (1, 1))	/* ctan  */
#define DELTActanh CHOOSE(0, BUILD_COMPLEX (2, 2), BUILD_COMPLEX (2, 1), 0, BUILD_COMPLEX (2, 2), BUILD_COMPLEX (2, 1))	/* ctanh  */
#define DELTAerfc CHOOSE(0, 24, 12, 0, 24, 12)	/* erfc  */
#define DELTAexp10 CHOOSE(0, 6, 2, 0, 6, 2)	/* exp10  */
#define DELTAexpm1 CHOOSE(0, 0, 1, 0, 0, 1)	/* expm1  */
#define DELTAfmod CHOOSE(0, 2, 1, 0, 2, 1)	/* fmod  */
#define DELTAhypot CHOOSE(0, 1, 1, 0, 1, 1)	/* hypot  */
#define DELTAj0 CHOOSE(0, 2, 2, 0, 2, 2)	/* j0  */
#define DELTAj1 CHOOSE(0, 1, 2, 0, 1, 2)	/* j1  */
#define DELTAjn CHOOSE(0, 6, 4, 0, 6, 4)	/* jn  */
#define DELTAlgamma CHOOSE(0, 1, 2, 0, 1, 2)	/* lgamma  */
#define DELTAlog CHOOSE(0, 1, 1, 0, 1, 1)	/* log  */
#define DELTAlog10 CHOOSE(0, 1, 1, 0, 1, 1)	/* log10  */
#define DELTAlog1p CHOOSE(0, 1, 1, 0, 1, 1)	/* log1p  */
#define DELTAlog2 CHOOSE(0, 1, 1, 0, 1, 1)	/* log2  */
#define DELTAsincos CHOOSE(0, 1, 1, 0, 1, 1)	/* sincos  */
#define DELTAsinh CHOOSE(0, 1, 1, 0, 1, 1)	/* sinh  */
#define DELTAtan CHOOSE(0, 0.5, 0, 0, 0.5, 0)	/* tan  */
#define DELTAtanh CHOOSE(0, 1, 1, 0, 1, 1)	/* tanh  */
#define DELTAtgamma CHOOSE(0, 1, 1, 0, 1, 1)	/* tgamma  */
#define DELTAy0 CHOOSE(0, 2, 1, 0, 2, 1)	/* y0  */
#define DELTAy1 CHOOSE(0, 3, 2, 0, 3, 2)	/* y1  */
#define DELTAyn CHOOSE(0, 3, 2, 0, 3, 2)	/* yn  */

/* Error of single function calls.  */
#define DELTA26 CHOOSE(0, 0, 2, 0, 0, 2)	/* asin (0.5) == pi/6  */
#define DELTA27 CHOOSE(0, 0, 2, 0, 0, 2)	/* asin (-0.5) == -pi/6  */
#define DELTA266 CHOOSE(0, BUILD_COMPLEX (5, 3), BUILD_COMPLEX (1, 6), 0, BUILD_COMPLEX (5, 3), BUILD_COMPLEX (1, 6))	/* casinh (-2 - 3 i) == -1.9686379257930962917886650952454982 - 0.96465850440760279204541105949953237 i  */
#define DELTA305 CHOOSE(0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (3, 1), 0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (3, 1))	/* catan (-2 - 3 i) == -1.4099210495965755225306193844604208 - 0.22907268296853876629588180294200276 i  */
#define DELTA344 CHOOSE(0, BUILD_COMPLEX (4, 0), BUILD_COMPLEX (0, 4), 0, BUILD_COMPLEX (4, 0), BUILD_COMPLEX (0, 4))	/* catanh (-2 - 3 i) == -0.14694666622552975204743278515471595 - 1.3389725222944935611241935759091443 i  */
#define DELTA352 CHOOSE(0, 1, 0, 0, 1, 0)	/* cbrt (-27.0) == -3.0  */
#define DELTA393 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* ccos (-2 - 3 i) == -4.18962569096880723013255501961597373 - 9.10922789375533659797919726277886212 i  */
#define DELTA432 CHOOSE(0, 0, BUILD_COMPLEX (1, 1), 0, 0, BUILD_COMPLEX (1, 1))	/* ccosh (-2 - 3 i) == -3.72454550491532256547397070325597253 + 0.511822569987384608834463849801875634 i  */
#define DELTA532 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* cexp (-2.0 - 3.0 i) == -0.13398091492954261346140525546115575 - 0.019098516261135196432576240858800925 i  */
#define DELTA578 CHOOSE(0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (0, 3), 0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (0, 3))	/* clog (-2 - 3 i) == 1.2824746787307683680267437207826593 - 2.1587989303424641704769327722648368 i  */
#define DELTA584 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (inf + inf i) == inf + pi/4*log10(e) i  */
#define DELTA585 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (inf - inf i) == inf - pi/4*log10(e) i  */
#define DELTA586 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (0 + inf i) == inf + pi/2*log10(e) i  */
#define DELTA587 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (3 + inf i) == inf + pi/2*log10(e) i  */
#define DELTA588 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (-0 + inf i) == inf + pi/2*log10(e) i  */
#define DELTA589 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (-3 + inf i) == inf + pi/2*log10(e) i  */
#define DELTA590 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (0 - inf i) == inf - pi/2*log10(e) i  */
#define DELTA591 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (3 - inf i) == inf - pi/2*log10(e) i  */
#define DELTA592 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (-0 - inf i) == inf - pi/2*log10(e) i  */
#define DELTA593 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (-3 - inf i) == inf - pi/2*log10(e) i  */
#define DELTA594 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (-inf + 0 i) == inf + pi*log10(e) i  */
#define DELTA595 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (-inf + 1 i) == inf + pi*log10(e) i  */
#define DELTA596 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (-inf - 0 i) == inf - pi*log10(e) i  */
#define DELTA597 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* clog10 (-inf - 1 i) == inf - pi*log10(e) i  */
#define DELTA616 CHOOSE(0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (0, 5), 0, BUILD_COMPLEX (0, 1), BUILD_COMPLEX (0, 5))	/* clog10 (-2 - 3 i) == 0.556971676153418384603252578971164214 - 0.937554462986374708541507952140189646 i  */
#define DELTA645 CHOOSE(0, 1, 0.5, 0, 1, 0.5)	/* cos (M_PI_6l * 2.0) == 0.5  */
#define DELTA646 CHOOSE(0, 2, 1, 0, 2, 1)	/* cos (M_PI_6l * 4.0) == -0.5  */
#define DELTA647 CHOOSE(0, 0.2758, 0.3667, 0, 0.2758, 0.3667)	/* cos (pi/2) == 0  */
#define DELTA658 CHOOSE(0, BUILD_COMPLEX (0, 1.1031), BUILD_COMPLEX (0, 1.5), 0, BUILD_COMPLEX (0, 1.1031), BUILD_COMPLEX (0, 1.5))	/* cpow (e + 0 i, 0 + 2 * M_PIl i) == 1.0 + 0.0 i  */
#define DELTA659 CHOOSE(0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (4, 2), 0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (4, 2))	/* cpow (2 + 3 i, 4 + 0 i) == -119.0 - 120.0 i  */
#define DELTA760 CHOOSE(0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1), 0)	/* csinh (-2 - 3 i) == 3.59056458998577995201256544779481679 - 0.530921086248519805267040090660676560 i  */
#define DELTA801 CHOOSE(0, 0, BUILD_COMPLEX (1, 0), 0, 0, BUILD_COMPLEX (1, 0))	/* csqrt (-2 - 3 i) == 0.89597747612983812471573375529004348 - 1.6741492280355400404480393008490519 i  */
#define DELTA802 CHOOSE(0, 0, BUILD_COMPLEX (1, 0), 0, 0, BUILD_COMPLEX (1, 0))	/* csqrt (-2 + 3 i) == 0.89597747612983812471573375529004348 + 1.6741492280355400404480393008490519 i  */
#define DELTA836 CHOOSE(0, BUILD_COMPLEX (1, 0), 0, 0, BUILD_COMPLEX (1, 0), 0)	/* ctan (-2 - 3 i) == 0.376402564150424829275122113032269084e-2 - 1.00323862735360980144635859782192726 i  */
#define DELTA868 CHOOSE(0, 0, BUILD_COMPLEX (0, 1), 0, 0, BUILD_COMPLEX (0, 1))	/* ctanh (0 + pi/4 i) == 0.0 + 1.0 i  */
#define DELTA870 CHOOSE(0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (2, 0), 0, BUILD_COMPLEX (1, 0), BUILD_COMPLEX (2, 0))	/* ctanh (-2 - 3 i) == -0.965385879022133124278480269394560686 + 0.988437503832249372031403430350121098e-2 i  */
#define DELTA909 CHOOSE(0, 6, 2, 0, 6, 2)	/* exp10 (3) == 1000  */
#define DELTA910 CHOOSE(0, 2, 1, 0, 2, 1)	/* exp10 (-1) == 0.1  */
#define DELTA929 CHOOSE(0, 0, 1, 0, 0, 1)	/* expm1 (1) == M_El - 1.0  */
#define DELTA1145 CHOOSE(0, 0, 1, 0, 0, 1)	/* hypot (0.7, 12.4) == 12.419742348374220601176836866763271  */
#define DELTA1146 CHOOSE(0, 0, 1, 0, 0, 1)	/* hypot (-0.7, 12.4) == 12.419742348374220601176836866763271  */
#define DELTA1147 CHOOSE(0, 0, 1, 0, 0, 1)	/* hypot (0.7, -12.4) == 12.419742348374220601176836866763271  */
#define DELTA1148 CHOOSE(0, 0, 1, 0, 0, 1)	/* hypot (-0.7, -12.4) == 12.419742348374220601176836866763271  */
#define DELTA1149 CHOOSE(0, 0, 1, 0, 0, 1)	/* hypot (12.4, 0.7) == 12.419742348374220601176836866763271  */
#define DELTA1150 CHOOSE(0, 0, 1, 0, 0, 1)	/* hypot (-12.4, 0.7) == 12.419742348374220601176836866763271  */
#define DELTA1151 CHOOSE(0, 0, 1, 0, 0, 1)	/* hypot (12.4, -0.7) == 12.419742348374220601176836866763271  */
#define DELTA1152 CHOOSE(0, 0, 1, 0, 0, 1)	/* hypot (-12.4, -0.7) == 12.419742348374220601176836866763271  */
#define DELTA1265 CHOOSE(0, 1, 1, 0, 1, 1)	/* lgamma (0.7) == 0.260867246531666514385732417016759578  */
#define DELTA1267 CHOOSE(0, 1, 2, 0, 1, 2)	/* lgamma (1.2) == -0.853740900033158497197028392998854470e-1  */
#define DELTA1793 CHOOSE(0, 0, 1, 0, 0, 1)	/* log10 (e) == log10(e)  */
#define DELTA2582 CHOOSE(0, 0.2758, 0.3667, 0, 0.2758, 0.3667)	/* sincos (pi/2, &sin_res, &cos_res) puts 0 in cos_res  */
#define DELTA2586 CHOOSE(0, 1, 0.5, 0, 1, 0.5)	/* sincos (M_PI_6l*2.0, &sin_res, &cos_res) puts 0.5 in cos_res  */
#define DELTA2617 CHOOSE(0, 0.5, 0, 0, 0.5, 0)	/* tan (pi/4) == 1  */
#define DELTA2635 CHOOSE(0, 0, 1, 0, 0, 1)	/* tgamma (0.5) == sqrt (pi)  */
#define DELTA2636 CHOOSE(0, 1, 1, 0, 1, 1)	/* tgamma (-0.5) == -2 sqrt (pi)  */
#define DELTA2639 CHOOSE(0, 1, 1, 0, 1, 1)	/* tgamma (0.7) == 1.29805533264755778568117117915281162  */
