#!/bin/sh

cp ptxconfig ptxconfig.orig
sed -i -e "s|^PTXCONF_PREFIX=\"\(.*\)$|PTXCONF_PREFIX=\"${PTXDIST_AUTOBUILD_PREFIX}\1|g" ptxconfig

ptxdist go
retval=$?

mv ptxconfig.orig ptxconfig

exit $retval

