"Compiled on a Darwin 17.5.0 system on 2018-05-16.\n"
"Available extensions:\n"
"	crypt add-on version 2.1 by Michael Glad and others\n"
"	Native POSIX Threads Library by Ulrich Drepper et al\n"
"	Support for some architectures added on, not maintained in glibc core.\n"
"	BIND-8.2.3-T5B\n"
