# -*-makefile-*-

PTXCONF_GLIBC_HEADERS_FAKE_CROSS		:= $(call remove_quotes, $(PTXCONF_GLIBC_HEADERS_FAKE_CROSS))
PTXCONF_GLIBC_EXTRA_CONFIG			:= $(call remove_quotes, $(PTXCONF_GLIBC_EXTRA_CONFIG))

PTXCONF_CROSS_GCC_EXTRA_CONFIG			:= $(call remove_quotes, $(PTXCONF_CROSS_GCC_EXTRA_CONFIG))
PTXCONF_CROSS_GCC_EXTRA_CONFIG_LIBC		:= $(call remove_quotes, $(PTXCONF_CROSS_GCC_EXTRA_CONFIG_LIBC))
PTXCONF_CROSS_GCC_EXTRA_CONFIG_CXA_ATEXIT	:= $(call remove_quotes, $(PTXCONF_CROSS_GCC_EXTRA_CONFIG_CXA_ATEXIT))
PTXCONF_CROSS_GCC_EXTRA_CONFIG_SHARED		:= $(call remove_quotes, $(PTXCONF_CROSS_GCC_EXTRA_CONFIG_SHARED))
PTXCONF_ARCH					:= $(call remove_quotes, $(PTXCONF_ARCH))


CROSS_GCC_FIRST_PREFIX	:= $(PTXCONF_SYSROOT_CROSS)/gcc-first
CROSS_PATH		:= $(PTXCONF_SYSROOT_CROSS)/bin:$(PTXCONF_SYSROOT_CROSS)/sbin:$(CROSS_GCC_FIRST_PREFIX)/bin:$$PATH

ifdef PTXCONF_TOOLCHAIN_DEBUG
BUILDDIR_DEBUG		:= $(PTXCONF_SYSROOT_CROSS)/src/target
BUILDDIR_CROSS_DEBUG	:= $(PTXCONF_SYSROOT_CROSS)/src/cross
else
BUILDDIR_DEBUG		:= $(BUILDDIR)
BUILDDIR_CROSS_DEBUG	:= $(CROSS_BUILDDIR)
endif

# vim: syntax=make
