# generated by configure / remove this line to disable regeneration
prefix="/opt/cross"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/opt/cross/c4ev3/build-gcc/isl/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/opt/cross/c4ev3/build-gcc/isl/../../gcc-8.1.0/isl/include"
package="isl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "isl"
;; --help) pkg-config --help ; echo Buildscript Of "isl Library"
;; --modversion|--version) echo "0.18"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lisl /opt/cross/c4ev3/build-gcc/./gmp/libgmp.la"
       :
;; --cflags) echo -I${includedir} "-I/opt/cross/c4ev3/build-gcc/gmp/../../gcc-8.1.0/gmp -I/opt/cross/c4ev3/build-gcc/./gmp"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
