/* This file is automatically generated by abi-versions.awk.
   It defines symbols used by shlib-compat.h, which see.  */

#ifndef _ABI_VERSIONS_H
#define _ABI_VERSIONS_H

/* start libBrokenLocale */
#define ABI_libBrokenLocale_GLIBC_2_0	ABI_libBrokenLocale_GLIBC_2_4
#define VERSION_libBrokenLocale_GLIBC_2_0	GLIBC_2.4
#define ABI_libBrokenLocale_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libBrokenLocale_GLIBC_2_4	GLIBC_2.4
/* end libBrokenLocale */

/* start libc */
#define ABI_libc_GLIBC_2_0	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_0	GLIBC_2.4
#define ABI_libc_GLIBC_2_1	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_1	GLIBC_2.4
#define ABI_libc_GLIBC_2_1_1	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_1_1	GLIBC_2.4
#define ABI_libc_GLIBC_2_1_2	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_1_2	GLIBC_2.4
#define ABI_libc_GLIBC_2_1_3	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_1_3	GLIBC_2.4
#define ABI_libc_GLIBC_2_1_4	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_1_4	GLIBC_2.4
#define ABI_libc_GLIBC_2_2	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_2	GLIBC_2.4
#define ABI_libc_GLIBC_2_2_1	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_2_1	GLIBC_2.4
#define ABI_libc_GLIBC_2_2_2	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_2_2	GLIBC_2.4
#define ABI_libc_GLIBC_2_2_3	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_2_3	GLIBC_2.4
#define ABI_libc_GLIBC_2_2_4	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_2_4	GLIBC_2.4
#define ABI_libc_GLIBC_2_2_5	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_2_5	GLIBC_2.4
#define ABI_libc_GLIBC_2_2_6	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_2_6	GLIBC_2.4
#define ABI_libc_GLIBC_2_3	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_3	GLIBC_2.4
#define ABI_libc_GLIBC_2_3_1	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_3_1	GLIBC_2.4
#define ABI_libc_GLIBC_2_3_2	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_3_2	GLIBC_2.4
#define ABI_libc_GLIBC_2_3_3	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_3_3	GLIBC_2.4
#define ABI_libc_GLIBC_2_3_4	ABI_libc_GLIBC_2_4
#define VERSION_libc_GLIBC_2_3_4	GLIBC_2.4
#define ABI_libc_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libc_GLIBC_2_4	GLIBC_2.4
#define ABI_libc_GLIBC_2_5	2	/* support GLIBC_2.5 */
#define VERSION_libc_GLIBC_2_5	GLIBC_2.5
#define ABI_libc_GLIBC_2_6	3	/* support GLIBC_2.6 */
#define VERSION_libc_GLIBC_2_6	GLIBC_2.6
#define ABI_libc_GLIBC_2_7	4	/* support GLIBC_2.7 */
#define VERSION_libc_GLIBC_2_7	GLIBC_2.7
#define ABI_libc_GLIBC_2_8	5	/* support GLIBC_2.8 */
#define VERSION_libc_GLIBC_2_8	GLIBC_2.8
#define ABI_libc_HURD_CTHREADS_0_3	6	/* support HURD_CTHREADS_0.3 */
#define VERSION_libc_HURD_CTHREADS_0_3	HURD_CTHREADS_0.3
#define ABI_libc_GLIBC_PRIVATE	7	/* support GLIBC_PRIVATE */
#define VERSION_libc_GLIBC_PRIVATE	GLIBC_PRIVATE
/* end libc */

/* start libcrypt */
#define ABI_libcrypt_GLIBC_2_0	ABI_libcrypt_GLIBC_2_4
#define VERSION_libcrypt_GLIBC_2_0	GLIBC_2.4
#define ABI_libcrypt_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libcrypt_GLIBC_2_4	GLIBC_2.4
/* end libcrypt */

/* start libdl */
#define ABI_libdl_GLIBC_2_0	ABI_libdl_GLIBC_2_4
#define VERSION_libdl_GLIBC_2_0	GLIBC_2.4
#define ABI_libdl_GLIBC_2_1	ABI_libdl_GLIBC_2_4
#define VERSION_libdl_GLIBC_2_1	GLIBC_2.4
#define ABI_libdl_GLIBC_2_3_3	ABI_libdl_GLIBC_2_4
#define VERSION_libdl_GLIBC_2_3_3	GLIBC_2.4
#define ABI_libdl_GLIBC_2_3_4	ABI_libdl_GLIBC_2_4
#define VERSION_libdl_GLIBC_2_3_4	GLIBC_2.4
#define ABI_libdl_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libdl_GLIBC_2_4	GLIBC_2.4
/* end libdl */

/* start libm */
#define ABI_libm_GLIBC_2_0	ABI_libm_GLIBC_2_4
#define VERSION_libm_GLIBC_2_0	GLIBC_2.4
#define ABI_libm_GLIBC_2_1	ABI_libm_GLIBC_2_4
#define VERSION_libm_GLIBC_2_1	GLIBC_2.4
#define ABI_libm_GLIBC_2_2	ABI_libm_GLIBC_2_4
#define VERSION_libm_GLIBC_2_2	GLIBC_2.4
#define ABI_libm_GLIBC_2_2_3	ABI_libm_GLIBC_2_4
#define VERSION_libm_GLIBC_2_2_3	GLIBC_2.4
#define ABI_libm_GLIBC_2_3_4	ABI_libm_GLIBC_2_4
#define VERSION_libm_GLIBC_2_3_4	GLIBC_2.4
#define ABI_libm_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libm_GLIBC_2_4	GLIBC_2.4
/* end libm */

/* start libnsl */
#define ABI_libnsl_GLIBC_2_0	ABI_libnsl_GLIBC_2_4
#define VERSION_libnsl_GLIBC_2_0	GLIBC_2.4
#define ABI_libnsl_GLIBC_2_1	ABI_libnsl_GLIBC_2_4
#define VERSION_libnsl_GLIBC_2_1	GLIBC_2.4
#define ABI_libnsl_GLIBC_2_2	ABI_libnsl_GLIBC_2_4
#define VERSION_libnsl_GLIBC_2_2	GLIBC_2.4
#define ABI_libnsl_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libnsl_GLIBC_2_4	GLIBC_2.4
/* end libnsl */

/* start libnss_compat */
#define ABI_libnss_compat_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_compat_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_compat_GLIBC_2_4	2	/* support GLIBC_2.4 */
#define VERSION_libnss_compat_GLIBC_2_4	GLIBC_2.4
/* end libnss_compat */

/* start libnss_dns */
#define ABI_libnss_dns_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_dns_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_dns_GLIBC_2_4	2	/* support GLIBC_2.4 */
#define VERSION_libnss_dns_GLIBC_2_4	GLIBC_2.4
/* end libnss_dns */

/* start libnss_files */
#define ABI_libnss_files_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_files_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_files_GLIBC_2_4	2	/* support GLIBC_2.4 */
#define VERSION_libnss_files_GLIBC_2_4	GLIBC_2.4
/* end libnss_files */

/* start libnss_hesiod */
#define ABI_libnss_hesiod_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_hesiod_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_hesiod_GLIBC_2_4	2	/* support GLIBC_2.4 */
#define VERSION_libnss_hesiod_GLIBC_2_4	GLIBC_2.4
/* end libnss_hesiod */

/* start libnss_nis */
#define ABI_libnss_nis_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_nis_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_nis_GLIBC_2_4	2	/* support GLIBC_2.4 */
#define VERSION_libnss_nis_GLIBC_2_4	GLIBC_2.4
/* end libnss_nis */

/* start libnss_nisplus */
#define ABI_libnss_nisplus_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libnss_nisplus_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libnss_nisplus_GLIBC_2_4	2	/* support GLIBC_2.4 */
#define VERSION_libnss_nisplus_GLIBC_2_4	GLIBC_2.4
/* end libnss_nisplus */

/* start libpthread */
#define ABI_libpthread_GLIBC_2_0	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_0	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_1	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_1	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_1_1	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_1_1	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_1_2	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_1_2	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_2	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_2	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_2_3	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_2_3	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_2_6	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_2_6	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_3_2	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_3_2	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_3_3	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_3_3	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_3_4	ABI_libpthread_GLIBC_2_4
#define VERSION_libpthread_GLIBC_2_3_4	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libpthread_GLIBC_2_4	GLIBC_2.4
#define ABI_libpthread_GLIBC_2_6	2	/* support GLIBC_2.6 */
#define VERSION_libpthread_GLIBC_2_6	GLIBC_2.6
#define ABI_libpthread_GLIBC_PRIVATE	3	/* support GLIBC_PRIVATE */
#define VERSION_libpthread_GLIBC_PRIVATE	GLIBC_PRIVATE
/* end libpthread */

/* start libresolv */
#define ABI_libresolv_GLIBC_2_0	ABI_libresolv_GLIBC_2_4
#define VERSION_libresolv_GLIBC_2_0	GLIBC_2.4
#define ABI_libresolv_GLIBC_2_2	ABI_libresolv_GLIBC_2_4
#define VERSION_libresolv_GLIBC_2_2	GLIBC_2.4
#define ABI_libresolv_GLIBC_2_3_2	ABI_libresolv_GLIBC_2_4
#define VERSION_libresolv_GLIBC_2_3_2	GLIBC_2.4
#define ABI_libresolv_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libresolv_GLIBC_PRIVATE	GLIBC_PRIVATE
#define ABI_libresolv_GLIBC_2_4	2	/* support GLIBC_2.4 */
#define VERSION_libresolv_GLIBC_2_4	GLIBC_2.4
/* end libresolv */

/* start librt */
#define ABI_librt_GLIBC_2_1	ABI_librt_GLIBC_2_4
#define VERSION_librt_GLIBC_2_1	GLIBC_2.4
#define ABI_librt_GLIBC_2_2	ABI_librt_GLIBC_2_4
#define VERSION_librt_GLIBC_2_2	GLIBC_2.4
#define ABI_librt_GLIBC_2_3	ABI_librt_GLIBC_2_4
#define VERSION_librt_GLIBC_2_3	GLIBC_2.4
#define ABI_librt_GLIBC_2_3_3	ABI_librt_GLIBC_2_4
#define VERSION_librt_GLIBC_2_3_3	GLIBC_2.4
#define ABI_librt_GLIBC_2_3_4	ABI_librt_GLIBC_2_4
#define VERSION_librt_GLIBC_2_3_4	GLIBC_2.4
#define ABI_librt_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_librt_GLIBC_2_4	GLIBC_2.4
#define ABI_librt_GLIBC_2_7	2	/* support GLIBC_2.7 */
#define VERSION_librt_GLIBC_2_7	GLIBC_2.7
/* end librt */

/* start libutil */
#define ABI_libutil_GLIBC_2_0	ABI_libutil_GLIBC_2_4
#define VERSION_libutil_GLIBC_2_0	GLIBC_2.4
#define ABI_libutil_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libutil_GLIBC_2_4	GLIBC_2.4
/* end libutil */

/* start ld */
#define ABI_ld_GLIBC_2_0	ABI_ld_GLIBC_2_4
#define VERSION_ld_GLIBC_2_0	GLIBC_2.4
#define ABI_ld_GLIBC_2_1	ABI_ld_GLIBC_2_4
#define VERSION_ld_GLIBC_2_1	GLIBC_2.4
#define ABI_ld_GLIBC_2_3	ABI_ld_GLIBC_2_4
#define VERSION_ld_GLIBC_2_3	GLIBC_2.4
#define ABI_ld_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_ld_GLIBC_2_4	GLIBC_2.4
#define ABI_ld_GLIBC_PRIVATE	2	/* support GLIBC_PRIVATE */
#define VERSION_ld_GLIBC_PRIVATE	GLIBC_PRIVATE
/* end ld */

/* start libthread_db */
#define ABI_libthread_db_GLIBC_2_1_3	ABI_libthread_db_GLIBC_2_4
#define VERSION_libthread_db_GLIBC_2_1_3	GLIBC_2.4
#define ABI_libthread_db_GLIBC_2_2_3	ABI_libthread_db_GLIBC_2_4
#define VERSION_libthread_db_GLIBC_2_2_3	GLIBC_2.4
#define ABI_libthread_db_GLIBC_2_3	ABI_libthread_db_GLIBC_2_4
#define VERSION_libthread_db_GLIBC_2_3	GLIBC_2.4
#define ABI_libthread_db_GLIBC_2_3_3	ABI_libthread_db_GLIBC_2_4
#define VERSION_libthread_db_GLIBC_2_3_3	GLIBC_2.4
#define ABI_libthread_db_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libthread_db_GLIBC_2_4	GLIBC_2.4
/* end libthread_db */

/* start libanl */
#define ABI_libanl_GLIBC_2_2_3	ABI_libanl_GLIBC_2_4
#define VERSION_libanl_GLIBC_2_2_3	GLIBC_2.4
#define ABI_libanl_GLIBC_2_4	1	/* support GLIBC_2.4 */
#define VERSION_libanl_GLIBC_2_4	GLIBC_2.4
/* end libanl */

/* start libcidn */
#define ABI_libcidn_GLIBC_PRIVATE	1	/* support GLIBC_PRIVATE */
#define VERSION_libcidn_GLIBC_PRIVATE	GLIBC_PRIVATE
/* end libcidn */

#endif /* abi-versions.h */
