#!/bin/sh

#
# This script computes the various flags needed to run GNU C++ testsuites
# (compiler specific as well as library specific). 
#
# Written by Benjamin Kosnik <bkoz@redhat.com>
#            Gabriel Dos Reis <gdr@codesourcery.com>
#

# Print a message saying how this script is intended to be invoked
print_usage() {
    cat <<EOF
Usage: 
    testsuite_flags --install-includes
		    --build-includes
		    --build-cxx
		    --build-cc
		    --install-cxx
		    --cxxflags
		    --cxxldflags
		    --cxxpchflags
		    --cxxvtvflags

EOF
}

# Establish configure-generated directory structure.
BUILD_DIR=/opt/cross/c4ev3/build-gcc/arm-linux-gnueabi/libstdc++-v3
SRC_DIR=/opt/cross/c4ev3/gcc-8.1.0/libstdc++-v3
PREFIX_DIR=/opt/cross
query=$1

case ${query} in
    --install-includes)
      INCLUDES="-I${SRC_DIR}/testsuite/util"
      echo ${INCLUDES}
      ;;
    --build-includes)
      INCLUDES="-nostdinc++ -I/opt/cross/c4ev3/build-gcc/arm-linux-gnueabi/libstdc++-v3/include/arm-linux-gnueabi -I/opt/cross/c4ev3/build-gcc/arm-linux-gnueabi/libstdc++-v3/include -I/opt/cross/c4ev3/gcc-8.1.0/libstdc++-v3/libsupc++ 
                -I${SRC_DIR}/include/backward -I${SRC_DIR}/testsuite/util"
      echo ${INCLUDES}
      ;;
    --install-cxx)
      CXX=${PREFIX_DIR}/bin/g++
      echo ${CXX}
      ;;
    --build-cxx)
      CXX_build=" /opt/cross/c4ev3/build-gcc/./gcc/xgcc -shared-libgcc -B/opt/cross/c4ev3/build-gcc/./gcc -nostdinc++ -L/opt/cross/c4ev3/build-gcc/arm-linux-gnueabi/libstdc++-v3/src -L/opt/cross/c4ev3/build-gcc/arm-linux-gnueabi/libstdc++-v3/src/.libs -L/opt/cross/c4ev3/build-gcc/arm-linux-gnueabi/libstdc++-v3/libsupc++/.libs -B/opt/cross/arm-linux-gnueabi/bin/ -B/opt/cross/arm-linux-gnueabi/lib/ -isystem /opt/cross/arm-linux-gnueabi/include -isystem /opt/cross/arm-linux-gnueabi/sys-include   "
      CXX=`echo "$CXX_build" | sed 's,gcc/xgcc ,gcc/xg++ ,'`
      echo ${CXX}
      ;;
    --build-cc)
      CC_build="/opt/cross/c4ev3/build-gcc/./gcc/xgcc -B/opt/cross/c4ev3/build-gcc/./gcc/ -B/opt/cross/arm-linux-gnueabi/bin/ -B/opt/cross/arm-linux-gnueabi/lib/ -isystem /opt/cross/arm-linux-gnueabi/include -isystem /opt/cross/arm-linux-gnueabi/sys-include   "
      CC="$CC_build"
      echo ${CC}
      ;;
    --cxxflags)
      CXXFLAGS_default="-fmessage-length=0 -fno-show-column"
      CXXFLAGS_config="-ffunction-sections -fdata-sections  "
      echo ${CXXFLAGS_default} ${CXXFLAGS_config} 
      ;;
    --cxxvtvflags)
      CXXFLAGS_vtv=""
      LDFLAGS_vtv=""
      echo ${CXXFLAGS_vtv} ${LDFLAGS_vtv}
      ;;
    --cxxparallelflags)
      CXXFLAGS_parallel="-D_GLIBCXX_PARALLEL -fopenmp
			 -B${BUILD_DIR}/../libgomp 
                         -I${BUILD_DIR}/../libgomp 
			 -L${BUILD_DIR}/../libgomp/.libs -lgomp"
      echo ${CXXFLAGS_parallel}
      ;;
    --cxxpchflags)
      PCHFLAGS="-include bits/stdc++.h"
      echo ${PCHFLAGS}
      ;;
    --cxxldflags)
      SECTIONLDFLAGS="-Wl,--gc-sections  
                      -L${BUILD_DIR}/src/filesystem/.libs"
      echo ${SECTIONLDFLAGS}
      ;;
    *)
      print_usage
      ;;
esac

exit 0
